console.log("Name: Cordell Rainock");
console.log("Career: Entrepreneur");
console.log("Description : BYU Business Strategy Alumni and Entrepreneur");
console.log(" ");
console.log("My Interests:");
console.log("* songwriting");
console.log("* grilling");
console.log("* mountain biking");
console.log("* golf");
console.log(" ");
console.log("My Previous Experience:");
console.log("* Owner of Archeio Systems--an archive imaging technology company");
console.log("* Pricing analyst at Intel");
console.log("* TA for business communications class");
console.log(" ");
console.log("My Skills:");
console.log("* UX/UI");
console.log("* economic/strategic analysis");
console.log("* HTML, CSS");
console.log("* Excel, PowerPoint, Word");